-- Criando um novo banco de dados
CREATE DATABASE SENAI_SVIGUFU_TARDE;

USE SENAI_SVIGUFU_TARDE;

CREATE TABLE TIPOS_EVENTOS(
    ID INT IDENTITY PRIMARY KEY 
	,TITULO VARCHAR(255) NOT NULL UNIQUE 
);

CREATE TABLE INSTITUICOES (
    ID INT IDENTITY PRIMARY KEY 
	,RAZAO_SOCIAL VARCHAR(255) NOT NULL
	,NOME_FANTASIA VARCHAR(255)
	,CNPJ CHAR(14) NOT NULL UNIQUE
	,LOGRADOURO VARCHAR(255) NOT NULL
	,CEP CHAR(8) NOT NULL
	,UE CHAR(2) NOT NULL
	,CIDADE VARCHAR(255) NOT NULL
);

CREATE TABLE EVENTOS (
    ID INT IDENTITY PRIMARY KEY
	,TITULO VARCHAR(255) NOT NULL
	,DESCRICAO TEXT
	,DATA_LIVRE DATETIME NOT NULL
	,ACESSO_LIVRE BIT DEFAULT(1) -- 1 TRUE // 0 FALSE
	,ID_TIPO_EVENTO INT 
	,ID_INSTITUICAO INT
	,FOREIGN KEY (ID_TIPO_EVENTO) REFERENCES TIPOS_EVENTOS(ID)
	,FOREIGN KEY (ID_INSTITUICAO) REFERENCES INSTITUICOES(ID)
);

CREATE TABLE USUARIOS(
    ID INT IDENTITY PRIMARY KEY
	,NOME VARCHAR(255) NOT NULL
	,EMAIL VARCHAR(255) NOT NULL UNIQUE
	,SENHA VARCHAR(255) NOT NULL
	,TIPO_USUARIO VARCHAR(100) NOT NULL
);

CREATE TABLE CONVITES(
    ID INT IDENTITY PRIMARY KEY 
	,ID_USUARIO INT FOREIGN KEY REFERENCES USUARIOS(ID)
	,ID_EVENTO INT FOREIGN KEY REFERENCES EVENTOS(ID)
	,SITUACAO CHAR(1)
);